//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAMigrate.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_NEW")]
        public string NewTemplateMark {
            get {
                return ((string)(this["NewTemplateMark"]));
            }
            set {
                this["NewTemplateMark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public byte NewTemplateMarkPosition {
            get {
                return ((byte)(this["NewTemplateMarkPosition"]));
            }
            set {
                this["NewTemplateMarkPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_OLD")]
        public string OldTemplateMark {
            get {
                return ((string)(this["OldTemplateMark"]));
            }
            set {
                this["OldTemplateMark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public byte OldTemplateMarkPosition {
            get {
                return ((byte)(this["OldTemplateMarkPosition"]));
            }
            set {
                this["OldTemplateMarkPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Brute")]
        public string SheetDataBruteMark {
            get {
                return ((string)(this["SheetDataBruteMark"]));
            }
            set {
                this["SheetDataBruteMark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte SheetDataBruteMarkPosition {
            get {
                return ((byte)(this["SheetDataBruteMarkPosition"]));
            }
            set {
                this["SheetDataBruteMarkPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$templates")]
        public string OldTemplateConcatMark {
            get {
                return ((string)(this["OldTemplateConcatMark"]));
            }
            set {
                this["OldTemplateConcatMark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte OldTemplateConcatMarkPosition {
            get {
                return ((byte)(this["OldTemplateConcatMarkPosition"]));
            }
            set {
                this["OldTemplateConcatMarkPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Export")]
        public string SheetExportMark {
            get {
                return ((string)(this["SheetExportMark"]));
            }
            set {
                this["SheetExportMark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte SheetExportMarkPosition {
            get {
                return ((byte)(this["SheetExportMarkPosition"]));
            }
            set {
                this["SheetExportMarkPosition"] = value;
            }
        }
    }
}
